pub(crate) type Asset = (&'static str, &'static str);

#[rustfmt::skip]
pub(crate) const APP_ASSETS: &[Asset] = &[
    ("package.json", include_str!("../../../shippable/app/package.json")),
    ("index.html", include_str!("../../../shippable/app/index.html")),
    ("tsconfig.json", include_str!("../../../shippable/app/tsconfig.json")),
    ("tsconfig.node.json", include_str!("../../../shippable/app/tsconfig.node.json")),
    ("vite.config.ts", include_str!("../../../shippable/app/vite.config.ts")),
    ("svelte.config.js", include_str!("../../../shippable/app/svelte.config.js")),
    ("src/vite-env.d.ts", include_str!("../../../shippable/app/src/vite-env.d.ts")),
    ("src/main.ts", include_str!("../../../shippable/app/src/main.ts")),
    ("src/App.svelte", include_str!("../../../shippable/app/src/App.svelte")),
    ("src/app.css", include_str!("../../../shippable/app/src/app.css")),
    ("src/end-run.css", include_str!("../../../shippable/app/src/end-run.css")),
    ("src/components/EndRun.svelte", include_str!("../../../shippable/app/src/components/EndRun.svelte")),
    ("src/components/GameActionMetadata.svelte", include_str!("../../../shippable/app/src/components/GameActionMetadata.svelte")),
    ("src/components/GameInventory.svelte", include_str!("../../../shippable/app/src/components/GameInventory.svelte")),
    ("src/components/GameQueue.svelte", include_str!("../../../shippable/app/src/components/GameQueue.svelte")),
    ("src/components/GameTimeline.svelte", include_str!("../../../shippable/app/src/components/GameTimeline.svelte")),
    ("src/components/RunSkillChanges.svelte", include_str!("../../../shippable/app/src/components/RunSkillChanges.svelte")),
    ("src/components/RunTimelineComparison.svelte", include_str!("../../../shippable/app/src/components/RunTimelineComparison.svelte")),
    ("src/game/state.ts", include_str!("../../../shippable/app/src/game/state.ts")),
    ("src/game/saveState.ts", include_str!("../../../shippable/app/src/game/saveState.ts")),
    ("src/game/saveFlags.ts", include_str!("../../../shippable/app/src/game/saveFlags.ts")),
    ("src/game/persistence.ts", include_str!("../../../shippable/app/src/game/persistence.ts")),
    ("src/game/restoreRunSummary.ts", include_str!("../../../shippable/app/src/game/restoreRunSummary.ts")),
    ("src/game/migrations.ts", include_str!("../../../shippable/app/src/game/migrations.ts")),
    ("src/game/effects.ts", include_str!("../../../shippable/app/src/game/effects.ts")),
    ("src/game/engineConfig.ts", include_str!("../../../shippable/app/src/game/engineConfig.ts")),
    ("src/game/flagRuntime.ts", include_str!("../../../shippable/app/src/game/flagRuntime.ts")),
    ("src/game/itemRuntime.ts", include_str!("../../../shippable/app/src/game/itemRuntime.ts")),
    ("src/game/runSkillChanges.ts", include_str!("../../../shippable/app/src/game/runSkillChanges.ts")),
    ("src/game/runTimelineComparison.ts", include_str!("../../../shippable/app/src/game/runTimelineComparison.ts")),
    ("src/game/types.ts", include_str!("../../../shippable/app/src/game/types.ts")),
    ("src/game/runtime.ts", include_str!("../../../shippable/app/src/game/runtime.ts")),
    ("src/game/view.ts", include_str!("../../../shippable/app/src/game/view.ts")),
];

#[rustfmt::skip]
pub(crate) const ENGINE_ASSETS: &[Asset] = &[
    ("actions.ts", include_str!("../../../shippable/engine/actions.ts")),
    ("core.ts", include_str!("../../../shippable/engine/core.ts")),
    ("hooks.ts", include_str!("../../../shippable/engine/hooks.ts")),
    ("loop.ts", include_str!("../../../shippable/engine/loop.ts")),
    ("mechanics/energy.ts", include_str!("../../../shippable/engine/mechanics/energy.ts")),
    ("mechanics/experience.ts", include_str!("../../../shippable/engine/mechanics/experience.ts")),
    ("mechanics/flags.ts", include_str!("../../../shippable/engine/mechanics/flags.ts")),
    ("mechanics/gameData.ts", include_str!("../../../shippable/engine/mechanics/gameData.ts")),
    ("mechanics/items.ts", include_str!("../../../shippable/engine/mechanics/items.ts")),
    ("mechanics/locations.ts", include_str!("../../../shippable/engine/mechanics/locations.ts")),
    ("mechanics/queue.ts", include_str!("../../../shippable/engine/mechanics/queue.ts")),
    ("mechanics/reveal.ts", include_str!("../../../shippable/engine/mechanics/reveal.ts")),
    ("mechanics/skills.ts", include_str!("../../../shippable/engine/mechanics/skills.ts")),
];

#[rustfmt::skip]
pub(crate) const GLASS_ASSETS: &[Asset] = &[
    ("index.ts", include_str!("../../../template/glass/index.ts")),
    ("Preview.svelte", include_str!("../../../template/glass/Preview.svelte")),
    ("components/ActionCard.svelte", include_str!("../../../template/glass/components/ActionCard.svelte")),
    ("components/ActionControl.svelte", include_str!("../../../template/glass/components/ActionControl.svelte")),
    ("components/ActionMetadata.svelte", include_str!("../../../template/glass/components/ActionMetadata.svelte")),
    ("components/GameShell.svelte", include_str!("../../../template/glass/components/GameShell.svelte")),
    ("components/GlassButton.svelte", include_str!("../../../template/glass/components/GlassButton.svelte")),
    ("components/GlassCard.svelte", include_str!("../../../template/glass/components/GlassCard.svelte")),
    ("components/GlassIconButton.svelte", include_str!("../../../template/glass/components/GlassIconButton.svelte")),
    ("components/GlassPanel.svelte", include_str!("../../../template/glass/components/GlassPanel.svelte")),
    ("components/GlassProgress.svelte", include_str!("../../../template/glass/components/GlassProgress.svelte")),
    ("components/GlassRoot.svelte", include_str!("../../../template/glass/components/GlassRoot.svelte")),
    ("components/GlassStat.svelte", include_str!("../../../template/glass/components/GlassStat.svelte")),
    ("components/ScrollArea.svelte", include_str!("../../../template/glass/components/ScrollArea.svelte")),
    ("components/RunStatus.svelte", include_str!("../../../template/glass/components/RunStatus.svelte")),
    ("components/SkillCard.svelte", include_str!("../../../template/glass/components/SkillCard.svelte")),
    ("runtime/glassGlow.ts", include_str!("../../../template/glass/runtime/glassGlow.ts")),
    ("runtime/glassController.ts", include_str!("../../../template/glass/runtime/glassController.ts")),
    ("runtime/glassFadePainter.ts", include_str!("../../../template/glass/runtime/glassFadePainter.ts")),
    ("runtime/glassGeometry.ts", include_str!("../../../template/glass/runtime/glassGeometry.ts")),
    ("runtime/glassReflectionCanvas.ts", include_str!("../../../template/glass/runtime/glassReflectionCanvas.ts")),
    ("runtime/glassReflectionPainter.ts", include_str!("../../../template/glass/runtime/glassReflectionPainter.ts")),
    ("runtime/glassTargets.ts", include_str!("../../../template/glass/runtime/glassTargets.ts")),
    ("runtime/glassTypes.ts", include_str!("../../../template/glass/runtime/glassTypes.ts")),
    ("runtime/scrollFade.ts", include_str!("../../../template/glass/runtime/scrollFade.ts")),
    ("styles/action-card.css", include_str!("../../../template/glass/styles/action-card.css")),
    ("styles/action-details.css", include_str!("../../../template/glass/styles/action-details.css")),
    ("styles/skill-card.css", include_str!("../../../template/glass/styles/skill-card.css")),
    ("styles/controls.css", include_str!("../../../template/glass/styles/controls.css")),
    ("styles/glass.css", include_str!("../../../template/glass/styles/glass.css")),
    ("styles/index.css", include_str!("../../../template/glass/styles/index.css")),
    ("styles/tokens.css", include_str!("../../../template/glass/styles/tokens.css")),
    ("styles/utilities.css", include_str!("../../../template/glass/styles/utilities.css")),
];
