[package]
name = "cancels"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
hyper = { version = "0.14.26", features = ["full"] }
http = "1.0"
tokio-util = "0.7.8"
futures-util = "0.3.28"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
colored = "2"
termsize = "0.1"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
hyper-tungstenite = "=0.5.0"
urlencoding = "=2.1.2"
log = { version = "0.4.0", features = ["std"] }
url = "2.2.2"
multer = "3.1.0"
