[package]
name = "main"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "grindfesta-engine"
path = "src/main.rs"

[dependencies]
cancels = { path = "../cancels" }
services = { path = "../services" }
routes = { path = "../routes" }
tokio = { version = "1", features = ["full"] }
variables = { path = "../variables" }
